/** Community feed seed: 12 posts (mixed Arabic/English), exactly one HELP post. */
export const seedPosts = [
  {
    id: 'post1',
    authorId: 'u2',
    type: 'GENERAL',
    body: 'My monstera finally unfurled a new leaf this morning! 🌿',
    images: ['assets/demo/plant-4.jpg'],
    attachment: null,
    createdAt: '2026-08-05T09:00:00.000Z',
  },
  {
    id: 'post2',
    authorId: 'u3',
    type: 'HELP',
    body: 'أوراق البندورة عم تصفرّ من تحت، شو ممكن يكون السبب؟',
    images: ['assets/demo/plant-2.jpg'],
    attachment: { imageUri: 'assets/demo/plant-2.jpg', topIssue: 'Early blight', confidence: 0.71 },
    createdAt: '2026-08-04T18:30:00.000Z',
  },
  {
    id: 'post3',
    authorId: 'u1',
    type: 'GENERAL',
    body: 'زرعت حبق عالبلكون وريحتو بتجنن 😍',
    images: ['assets/demo/plant-1.jpg'],
    attachment: null,
    createdAt: '2026-08-04T11:20:00.000Z',
  },
  {
    id: 'post4',
    authorId: 'u3',
    type: 'GENERAL',
    body: 'Olive harvest is coming early this year in the Bekaa — sharing my pruning tips soon.',
    images: [],
    attachment: null,
    createdAt: '2026-08-03T15:45:00.000Z',
  },
  {
    id: 'post5',
    authorId: 'u2',
    type: 'GENERAL',
    body: 'قصيت شتلة النعنع وحطيتها بالمي، بعد أسبوع طلعت جذور!',
    images: ['assets/demo/plant-3.jpg'],
    attachment: null,
    createdAt: '2026-08-02T20:10:00.000Z',
  },
  {
    id: 'post6',
    authorId: 'u1',
    type: 'GENERAL',
    body: 'Does lavender survive the coastal humidity? Mine looks a bit sad in Beirut.',
    images: [],
    attachment: null,
    createdAt: '2026-08-01T13:00:00.000Z',
  },
  {
    id: 'post7',
    authorId: 'u3',
    type: 'GENERAL',
    body: 'أول تينة من شجرتنا هالموسم 🎉 الصبر إلو نتيجة',
    images: ['assets/demo/plant-6.jpg'],
    attachment: null,
    createdAt: '2026-07-30T17:25:00.000Z',
  },
  {
    id: 'post8',
    authorId: 'u2',
    type: 'GENERAL',
    body: 'Propagated three aloe pups today — happy to trade for mint cuttings!',
    images: ['assets/demo/plant-5.jpg'],
    attachment: null,
    createdAt: '2026-07-28T10:40:00.000Z',
  },
  {
    id: 'post9',
    authorId: 'u1',
    type: 'GENERAL',
    body: 'ريحة الياسمين عالسطح كل مسا شي بيريّح القلب',
    images: [],
    attachment: null,
    createdAt: '2026-07-26T19:50:00.000Z',
  },
  {
    id: 'post10',
    authorId: 'u2',
    type: 'GENERAL',
    body: 'Harvested rosemary for tonight’s focaccia — homegrown herbs hit different.',
    images: [],
    attachment: null,
    createdAt: '2026-07-24T18:05:00.000Z',
  },
  {
    id: 'post11',
    authorId: 'u3',
    type: 'GENERAL',
    body: 'تحذير لأهل البقاع: ليالي الأسبوع الجاي باردة، غطّوا الشتلات الصغيرة',
    images: [],
    attachment: null,
    createdAt: '2026-07-22T21:15:00.000Z',
  },
  {
    id: 'post12',
    authorId: 'u1',
    type: 'GENERAL',
    body: 'Two weeks of following the app’s watering schedule and zero yellow leaves. Convert.',
    images: [],
    attachment: null,
    createdAt: '2026-07-20T08:55:00.000Z',
  },
];

/** A few seed comments (post2 is the HELP thread). */
export const seedComments = [
  {
    id: 'c1',
    postId: 'post2',
    authorId: 'u2',
    body: 'جرب تسقي عند الجذور بس، وشيل الأوراق المصابة',
    createdAt: '2026-08-04T19:00:00.000Z',
  },
  {
    id: 'c2',
    postId: 'post2',
    authorId: 'u1',
    body: 'Looks like early blight — a copper spray helped my tomatoes.',
    createdAt: '2026-08-04T19:30:00.000Z',
  },
  {
    id: 'c3',
    postId: 'post1',
    authorId: 'u1',
    body: 'Beautiful! How often do you water it?',
    createdAt: '2026-08-05T09:20:00.000Z',
  },
];

export const seedLikes = [
  { postId: 'post1', userId: 'u1' },
  { postId: 'post1', userId: 'u3' },
  { postId: 'post2', userId: 'u1' },
  { postId: 'post3', userId: 'u2' },
  { postId: 'post5', userId: 'u1' },
];

export const seedFollows = [
  { followerId: 'u1', followeeId: 'u2' },
  { followerId: 'u3', followeeId: 'u1' },
];
